# LAB 1

In [2]:
import numpy as np
import pandas as pd

### Part 1:

In [3]:
data = pd.read_csv('dulieuxettuyendaihoc.csv')

print("Thông tin dữ liệu:")
print(data.info())
print("\nMô tả dữ liệu:")
print(data.describe(include='all'))

qualitative_vars = ['GT', 'DT', 'KV', 'KT']

quantitative_vars = [col for col in data.columns if col not in qualitative_vars]

print("\nDanh sách biến định tính:", qualitative_vars)
print("Danh sách biến định lượng:", quantitative_vars)

for col in qualitative_vars:
    data[col] = data[col].astype('category')

for col in quantitative_vars:
    data[col] = pd.to_numeric(data[col], errors='coerce')

for col in quantitative_vars:
    mean_value = data[col].mean()
    data[col] = data[col].fillna(mean_value)


for col in qualitative_vars:
    mode_value = data[col].mode()[0]
    data[col] = data[col].fillna(mode_value)


print("\nSố lượng giá trị thiếu sau khi xử lý:")
print(data.isnull().sum())

bins = [0, 5, 7, 10]
labels = ['Yếu', 'Trung bình', 'Giỏi']

score_columns = ['T1', 'L1', 'H1', 'S1', 'V1', 'X1', 'D1', 'N1',
                 'T2', 'L2', 'H2', 'S2', 'V2', 'X2', 'D2', 'N2',
                 'T6', 'L6', 'H6', 'S6', 'V6', 'X6', 'D6', 'N6']

for col in score_columns:
    if col in data.columns:
        data[col + '_cat'] = pd.cut(data[col], bins=bins, labels=labels, include_lowest=True)

if set(['DH1', 'DH2', 'DH3']).issubset(data.columns):
    data['Tong_DH'] = data[['DH1', 'DH2', 'DH3']].sum(axis=1)
    print("\nTổng điểm thi đại học (Tong_DH) đã được tính.")

if 'Tong_DH' in data.columns:
    bins_result = [0, 15, 20, 30]
    labels_result = ['Không đỗ', 'Xét tuyển', 'Đỗ đại học']
    data['Ket_qua'] = pd.cut(data['Tong_DH'], bins=bins_result, labels=labels_result, include_lowest=True)
    print("\nBiến kết quả (Ket_qua) đã được tạo dựa trên tổng điểm thi.")

print("\nDữ liệu sau khi xử lý (5 dòng đầu tiên):")
print(data.head())

data.to_csv('dulieuxettuyendaihoc_processed.csv', index=False)

Thông tin dữ liệu:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 56 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   STT     100 non-null    int64
 1   T1      100 non-null    float64
 2   L1      100 non-null    float64
 3   H1      100 non-null    float64
 4   S1      100 non-null    float64
 5   V1      100 non-null    float64
 6   X1      100 non-null    float64
 7   D1      100 non-null    float64
 8   N1      100 non-null    float64
 9   T2      100 non-null    float64
 10  L2      100 non-null    float64
 11  H2      100 non-null    float64
 12  S2      100 non-null    float64
 13  V2      100 non-null    float64
 14  X2      100 non-null    float64
 15  D2      100 non-null    float64
 16  N2      100 non-null    float64
 17  T3      100 non-null    float64
 18  L3      100 non-null    float64
 19  H3      100 non-null    float64
 20  S3      100 non-null    float64
 21  V3      100 non-null    float64
 22  X3      100 non-null    float64
 23  D3      100 non-null    float64
 24  N3      100 non-null    float64
 25  T4      100 non-null    float64
 26  L4      100 non-null    float64
 27  H4      100 non-null    float64
 28  S4      100 non-null    float64
 29  V4      100 non-null    float64
 30  X4      100 non-null    float64
 31  D4      100 non-null    float64
 32  N4      100 non-null    float64
 33  T5      100 non-null    float64
 34  L5      100 non-null    float64
 35  H5      100 non-null    float64
 36  S5      100 non-null    float64
 37  V5      100 non-null    float64
 38  X5      100 non-null    float64
 39  D5      100 non-null    float64
 40  N5      100 non-null    float64
 41  T6      100 non-null    float64
 42  L6      100 non-null    float64
 43  H6      100 non-null    float64
 44  S6      100 non-null    float64
 45  V6      100 non-null    float64
 46  X6      100 non-null    float64
 47  D6      100 non-null    float64
 48  N6      100 non-null    float64
 49  GT      100 non-null    object
 50  DT      3 non-null      float64
 51  KV      100 non-null    object
 52  DH1     100 non-null    float64
 53  DH2     100 non-null    float64
 54  DH3     100 non-null    float64
 55  KT      100 non-null    object
dtypes: float64(52), int64(1), object(3)
memory usage: 43.9+ KB
None

Mô tả dữ liệu:
               STT          T1          L1          H1          S1  \
count   100.000000  100.000000  100.000000  100.000000  100.000000
unique         NaN         NaN         NaN         NaN         NaN
top            NaN         NaN         NaN         NaN         NaN
freq           NaN         NaN         NaN         NaN         NaN
mean     50.500000    5.946000    5.824000    6.279000    6.504000
std      29.011492    1.608338    1.257713    1.423773    1.273976
min       1.000000    2.400000    1.800000    3.000000    1.900000
25%      25.750000    5.000000    4.975000    5.100000    5.675000
50%      50.500000    5.850000    5.900000    6.300000    6.700000
75%      75.250000    7.200000    6.825000    7.400000    7.425000
max     100.000000    9.300000    8.000000    9.100000    8.800000

                V1         X1          D1         N1          T2  ...  \
count   100.000000  100.00000  100.000000  100.00000  100.000000  ...
unique         NaN        NaN         NaN        NaN         NaN  ...
top            NaN        NaN         NaN        NaN         NaN  ...
freq           NaN        NaN         NaN        NaN         NaN  ...
mean      5.920000    6.61200    6.440000    5.47100    6.374000  ...
std       1.041658    1.34452    1.285034    1.39228    1.561443  ...
min       3.100000    3.10000    2.000000    2.80000    2.800000  ...
25%       5.375000    5.47500    5.750000    4.50000    5.300000  ...
50%       6.050000    6.90000    6.600000    5.30000    6.250000  ...
75%       6.600000    7.52500    7.300000    6.40000    7.525000  ...
max       8.700000    8.90000    8.800000    9.30000    9.600000  ...

                X6          D6         N6   GT        DT   KV         DH1  \
count   100.000000  100.000000  100.00000  100  3.000000  100  100.000000
unique         NaN         NaN        NaN    2       NaN    3         NaN
top            NaN         NaN        NaN    M       NaN    1         NaN
freq           NaN         NaN        NaN   52       NaN   60         NaN
mean      6.895000    6.739000    6.02400  NaN  2.666667  NaN    3.740000
std       1.315208    0.903517    1.08508  NaN  2.886751  NaN    1.424408
min       3.800000    4.400000    3.50000  NaN  1.000000  NaN    1.000000
25%       5.900000    6.100000    5.20000  NaN  1.000000  NaN    2.500000
50%       6.600000    6.800000    5.90000  NaN  1.000000  NaN    3.625000
75%       7.925000    7.325000    6.62500  NaN  3.500000  NaN    4.750000
max       9.600000    8.700000    8.70000  NaN  6.000000  NaN    7.000000

               DH2         DH3   KT
count   100.000000  100.000000  100
unique         NaN         NaN    5
top            NaN         NaN    A
freq           NaN         NaN   49
mean      4.255000    4.875000  NaN
std       1.060053    1.041136  NaN
min       1.500000    2.750000  NaN
25%       3.500000    4.250000  NaN
50%       4.125000    4.750000  NaN
75%       4.750000    5.500000  NaN
max       8.000000    8.000000  NaN

[11 rows x 56 columns]

Danh sách biến định tính: ['GT', 'DT', 'KV', 'KT']
Danh sách biến định lượng: ['STT', 'T1', 'L1', 'H1', 'S1', 'V1', 'X1', 'D1', 'N1', 'T2', 'L2', 'H2', 'S2', 'V2', 'X2', 'D2', 'N2', 'T3', 'L3', 'H3', 'S3', 'V3', 'X3', 'D3', 'N3', 'T4', 'L4', 'H4', 'S4', 'V4', 'X4', 'D4', 'N4', 'T5', 'L5', 'H5', 'S5', 'V5', 'X5', 'D5', 'N5', 'T6', 'L6', 'H6', 'S6', 'V6', 'X6', 'D6', 'N6', 'DH1', 'DH2', 'DH3']

Số lượng giá trị thiếu sau khi xử lý:
STT    0
T1     0
L1     0
H1     0
S1     0
V1     0
X1     0
D1     0
N1     0
T2     0
L2     0
H2     0
S2     0
V2     0
X2     0
D2     0
N2     0
T3     0
L3     0
H3     0
S3     0
V3     0
X3     0
D3     0
N3     0
T4     0
L4     0
H4     0
S4     0
V4     0
X4     0
D4     0
N4     0
T5     0
L5     0
H5     0
S5     0
V5     0
X5     0
D5     0
N5     0
T6     0
L6     0
H6     0
S6     0
V6     0
X6     0
D6     0
N6     0
GT     0
DT     0
KV     0
DH1    0
DH2    0
DH3    0
KT     0
dtype: int64

Tổng điểm thi đại học (Tong_DH) đã được tính.

Biến kết quả (Ket_qua) đã được tạo dựa trên tổng điểm thi.

Dữ liệu sau khi xử lý (5 dòng đầu tiên):
   STT   T1   L1   H1   S1   V1   X1   D1   N1   T2  ...      T6_cat  \
0    1  7.2  7.3  6.3  7.3  7.0  7.9  7.3  5.5  8.4  ...  Trung bình
1    2  5.4  3.9  3.9  4.0  5.4  5.4  5.3  2.8  6.3  ...         Yếu
2    3  5.6  6.8  7.2  7.5  4.3  7.4  5.8  3.2  5.0  ...  Trung bình
3    4  6.6  6.4  5.3  6.9  5.4  7.3  6.4  5.8  5.1  ...        Giỏi
4    5  6.0  5.0  6.0  7.3  6.5  7.7  7.9  6.1  5.4  ...        Giỏi

       L6_cat      H6_cat      S6_cat      V6_cat      X6_cat      D6_cat  \
0  Trung bình  Trung bình        Giỏi        Giỏi  Trung bình        Giỏi
1  Trung bình         Yếu  Trung bình  Trung bình  Trung bình  Trung bình
2  Trung bình  Trung bình  Trung bình         Yếu        Giỏi        Giỏi
3  Trung bình  Trung bình  Trung bình  Trung bình        Giỏi        Giỏi
4  Trung bình  Trung bình  Trung bình  Trung bình  Trung bình        Giỏi

       N6_cat  Tong_DH    Ket_qua
0  Trung bình    11.00   Không đỗ
1         Yếu    13.50   Không đỗ
2         Yếu    15.75  Xét tuyển
3        Giỏi    13.75   Không đỗ
4        Giỏi    13.75   Không đỗ

[5 rows x 82 columns]

### Part 2:

In [4]:
df = pd.read_csv('dulieuxettuyendaihoc.csv')

qualitative_vars = ['GT', 'DT', 'KV', 'KT']
quantitative_vars = [col for col in df.columns if col not in qualitative_vars]

for col in qualitative_vars:
    df[col] = df[col].astype('category')

print("Các biến định tính:", qualitative_vars)
print("Các biến định lượng:", quantitative_vars)
print("\n10 dòng đầu tiên của dữ liệu:")
print(df.head(10))
print("\n10 dòng cuối cùng của dữ liệu:")
print(df.tail(10))
print("\nThống kê dữ liệu thiếu cho cột 'DT':")
print(df['DT'].isnull().value_counts())
print("\nCác giá trị duy nhất trong cột 'DT':")
print(df['DT'].unique())

df['DT'] = df['DT'].cat.add_categories([0])
df['DT'] = df['DT'].fillna(0)

print("\nSau khi xử lý, thống kê dữ liệu thiếu cho cột 'DT':")
print(df['DT'].isnull().value_counts())
print("\nThống kê dữ liệu thiếu cho cột 'T1':")
print(df['T1'].isnull().value_counts())
print("\nCác giá trị duy nhất trong cột 'T1':")
print(df['T1'].unique())

mean_T1 = df['T1'].mean()
df['T1'] = df['T1'].fillna(mean_T1)

print("\nSau khi xử lý, thống kê dữ liệu thiếu cho cột 'T1':")
print(df['T1'].isnull().value_counts())

score_columns = ['T1', 'L1', 'H1', 'S1', 'V1', 'X1', 'D1', 'N1',
                 'T2', 'L2', 'H2', 'S2', 'V2', 'X2', 'D2', 'N2',
                 'T6', 'L6', 'H6', 'S6', 'V6', 'X6', 'D6', 'N6']

for col in score_columns:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].mean())

if set(['T1','L1','H1','S1','V1','X1','D1','N1']).issubset(df.columns):
    df['TBM1'] = (df['T1']*2 + df['L1'] + df['H1'] + df['S1'] + df['V1']*2 + df['X1'] + df['D1'] + df['N1']) / 10
if set(['T2','L2','H2','S2','V2','X2','D2','N2']).issubset(df.columns):
    df['TBM2'] = (df['T2']*2 + df['L2'] + df['H2'] + df['S2'] + df['V2']*2 + df['X2'] + df['D2'] + df['N2']) / 10
if set(['T6','L6','H6','S6','V6','X6','D6','N6']).issubset(df.columns):
    df['TBM3'] = (df['T6']*2 + df['L6'] + df['H6'] + df['S6'] + df['V6']*2 + df['X6'] + df['D6'] + df['N6']) / 10

def classify_grade(score):
    if score < 5.0:
        return 'Y'
    elif 5.0 <= score < 6.5:
        return 'TB'
    elif 6.5 <= score < 8.0:
        return 'K'
    elif 8.0 <= score < 9.0:
        return 'G'
    else:
        return 'XS'

if 'TBM1' in df.columns:
    df['XL1'] = df['TBM1'].apply(classify_grade)
if 'TBM2' in df.columns:
    df['XL2'] = df['TBM2'].apply(classify_grade)
if 'TBM3' in df.columns:
    df['XL3'] = df['TBM3'].apply(classify_grade)

def convert_to_US(score):
    return (score / 10) * 4

if 'TBM1' in df.columns:
    df['US_TBM1'] = df['TBM1'].apply(convert_to_US)
if 'TBM2' in df.columns:
    df['US_TBM2'] = df['TBM2'].apply(convert_to_US)
if 'TBM3' in df.columns:
    df['US_TBM3'] = df['TBM3'].apply(convert_to_US)

def evaluate_admission(row):
    if row['KT'] in ['A', 'A1']:
        avg_score = (row['DH1'] * 2 + row['DH2'] + row['DH3']) / 4
    elif row['KT'] == 'B':
        avg_score = (row['DH1'] + row['DH2'] * 2 + row['DH3']) / 4
    else:
        avg_score = (row['DH1'] + row['DH2'] + row['DH3']) / 3
    return 1 if avg_score >= 5.0 else 0

if set(['DH1', 'DH2', 'DH3']).issubset(df.columns) and 'KT' in df.columns:
    df['KQXT'] = df.apply(evaluate_admission, axis=1)

df.to_csv('processed_dulieuxettuyendaihoc.csv', index=False)
print("\nĐã lưu dữ liệu đã xử lý vào file 'processed_dulieuxettuyendaihoc.csv'.")

Các biến định tính: ['GT', 'DT', 'KV', 'KT']
Các biến định lượng: ['STT', 'T1', 'L1', 'H1', 'S1', 'V1', 'X1', 'D1', 'N1', 'T2', 'L2', 'H2', 'S2', 'V2', 'X2', 'D2', 'N2', 'T3', 'L3', 'H3', 'S3', 'V3', 'X3', 'D3', 'N3', 'T4', 'L4', 'H4', 'S4', 'V4', 'X4', 'D4', 'N4', 'T5', 'L5', 'H5', 'S5', 'V5', 'X5', 'D5', 'N5', 'T6', 'L6', 'H6', 'S6', 'V6', 'X6', 'D6', 'N6', 'DH1', 'DH2', 'DH3']

10 dòng đầu tiên của dữ liệu:
   STT   T1   L1   H1   S1   V1   X1   D1   N1   T2  ...   X6   D6   N6  GT  \
0    1  7.2  7.3  6.3  7.3  7.0  7.9  7.3  5.5  8.4  ...  6.6  7.6  5.9   F
1    2  5.4  3.9  3.9  4.0  5.4  5.4  5.3  2.8  6.3  ...  6.6  6.1  4.4   M
2    3  5.6  6.8  7.2  7.5  4.3  7.4  5.8  3.2  5.0  ...  7.9  8.1  4.6   M
3    4  6.6  6.4  5.3  6.9  5.4  7.3  6.4  5.8  5.1  ...  7.1  7.3  7.4   M
4    5  6.0  5.0  6.0  7.3  6.5  7.7  7.9  6.1  5.4  ...  6.1  7.5  7.2   M
5    6  9.3  7.6  7.9  8.6  7.0  7.3  7.7  7.9  9.6  ...  5.7  8.0  7.8   M
6    7  2.8  3.9  5.5  6.9  5.0  7.3  4.6  5.2  4.4  ...  6.6  6.0  6.0   F
7    8  8.3  6.0  7.6  5.1  7.5  4.7  5.8  7.2  6.7  ...  7.1  6.8  7.0   F
8    9  6.5  6.3  7.6  6.0  5.5  7.1  6.3  5.0  7.3  ...  9.1  7.9  6.1   F
9   10  7.3  5.9  4.7  7.1  6.7  7.9  6.7  7.7  8.0  ...  6.4  6.1  7.8   F

   DT   KV   DH1   DH2   DH3  KT
0 NaN  2NT  3.25  3.25  4.50  A1
1 NaN    1  6.00  4.00  3.50   C
2 NaN    1  5.00  6.75  4.00   C
3 NaN    1  4.25  4.25  5.25  D1
4 NaN  2NT  4.25  4.50  5.00   A
5 NaN    1  1.50  4.00  6.00  D1
6 NaN    2  6.50  6.75  5.25   C
7 NaN    2  3.75  4.50  4.25  D1
8 NaN    1  3.50  3.50  6.75  D1
9 NaN    1  4.00  4.75  5.50  D1

[10 rows x 56 columns]

10 dòng cuối cùng của dữ liệu:
    STT   T1   L1   H1   S1   V1   X1   D1   N1   T2  ...   X6   D6   N6  GT  \
90   91  8.1  7.7  9.1  8.5  6.1  8.6  8.8  7.3  8.8  ...  8.3  8.7  7.8   M
91   92  7.8  6.5  6.7  5.4  6.2  4.8  5.9  4.4  8.9  ...  7.2  7.4  7.0   M
92   93  5.0  6.6  6.5  7.2  5.8  6.7  6.4  6.0  6.8  ...  5.9  6.7  5.8   M
93   94  5.2  5.2  6.8  7.9  6.6  8.9  7.6  5.3  6.8  ...  8.7  7.8  5.0   M
94   95  5.8  5.9  7.6  6.1  5.3  8.1  6.1  5.0  6.4  ...  7.3  6.8  5.3   M
95   96  8.6  6.9  7.4  8.8  7.6  5.8  7.3  5.7  8.9  ...  6.3  6.1  6.2   F
96   97  3.7  5.4  6.0  5.1  5.5  3.9  6.1  4.4  4.1  ...  7.9  7.5  4.4   F
97   98  8.8  5.5  7.4  7.7  6.2  7.3  8.1  4.5  9.5  ...  9.6  8.4  5.8   M
98   99  2.7  1.8  3.4  5.3  4.5  7.9  4.9  3.8  2.8  ...  6.6  5.2  5.9   M
99  100  4.1  5.2  4.9  5.3  5.5  5.4  7.2  5.4  4.4  ...  5.6  6.6  5.8   M

    DT   KV   DH1   DH2   DH3  KT
90 NaN    2  6.25  4.00  6.50   A
91 NaN  2NT  4.75  4.75  4.50   A
92 NaN    1  3.25  5.25  4.25   A
93 NaN    1  3.50  4.25  5.00   A
94 NaN    1  4.25  2.50  4.75   A
95 NaN    1  5.25  1.50  6.25   C
96 NaN    1  5.25  3.75  4.75   C
97 NaN  2NT  7.00  8.00  4.00   C
98 NaN    1  5.00  3.50  5.50   C
99 NaN  2NT  5.25  2.50  4.25   C

[10 rows x 56 columns]

Thống kê dữ liệu thiếu cho cột 'DT':
DT
True     97
False     3
Name: count, dtype: int64

Các giá trị duy nhất trong cột 'DT':
[NaN, 1.0, 6.0]
Categories (2, float64): [1.0, 6.0]

Sau khi xử lý, thống kê dữ liệu thiếu cho cột 'DT':
DT
False    100
Name: count, dtype: int64

Thống kê dữ liệu thiếu cho cột 'T1':
T1
False    100
Name: count, dtype: int64

Các giá trị duy nhất trong cột 'T1':
[7.2 5.4 5.6 6.6 6.  9.3 2.8 8.3 6.5 7.3 5.2 7.9 4.9 7.1 2.5 8.8 8.2 3.9
 5.  5.3 2.4 3.6 8.1 6.3 4.5 7.6 2.6 6.4 4.7 3.4 4.4 4.3 7.  6.1 6.9 6.7
 5.5 6.2 7.5 3.  5.1 4.6 5.8 4.2 4.8 5.7 5.9 8.4 7.8 8.6 3.7 2.7 4.1]

Sau khi xử lý, thống kê dữ liệu thiếu cho cột 'T1':
T1
False    100
Name: count, dtype: int64

Đã lưu dữ liệu đã xử lý vào file 'processed_dulieuxettuyendaihoc.csv'.